### PR TITLE
Drop old tag_map domain.

### PR DESCRIPTION
**Pull request by cevian**
Renaming the old domain played havoc with the upgrade scripts since
the idempotent functions were re-defined on the new domain.

It's just cleaner to drop it.

The original dependencies were:

```
select pg_describe_object(classid, objid, objsubid)
  from pg_depend
  where refobjid = 'ps_trace.tag_map'::regtype;;

--------------------------------------------------------------------------------------
 type tag_map[]
 constraint tag_map_check
 column span_tags of table _ps_trace.span
 column resource_tags of table _ps_trace.span
 column tags of table _ps_trace.event
 column tags of table _ps_trace.link
 function _ps_trace.get_tag_id(tag_map,tag_k)
 operator #(tag_map,tag_k)
 function _ps_trace.has_tag(tag_map,tag_k)
 operator #?(tag_map,tag_k)
 function _ps_trace.match_jsonb_path_exists(tag_map,tag_op_jsonb_path_exists)
 operator ?(tag_map,tag_op_jsonb_path_exists)
 function _ps_trace.match_regexp_matches(tag_map,tag_op_regexp_matches)
 operator ?(tag_map,tag_op_regexp_matches)
 function _ps_trace.match_regexp_not_matches(tag_map,tag_op_regexp_not_matches)
 operator ?(tag_map,tag_op_regexp_not_matches)
 function _ps_trace.match_equals(tag_map,tag_op_equals)
 operator ?(tag_map,tag_op_equals)
 function _ps_trace.match_not_equals(tag_map,tag_op_not_equals)
 operator ?(tag_map,tag_op_not_equals)
 function _ps_trace.match_less_than(tag_map,tag_op_less_than)
 operator ?(tag_map,tag_op_less_than)
 function _ps_trace.match_less_than_or_equal(tag_map,tag_op_less_than_or_equal)
 operator ?(tag_map,tag_op_less_than_or_equal)
 function _ps_trace.match_greater_than(tag_map,tag_op_greater_than)
 operator ?(tag_map,tag_op_greater_than)
 function _ps_trace.match_greater_than_or_equal(tag_map,tag_op_greater_than_or_equal)
 operator ?(tag_map,tag_op_greater_than_or_equal)
 function jsonb(tag_map)
 function jsonb(tag_map,tag_k[])
 function val(tag_map,tag_k)
 function val_text(tag_map,tag_k)
 function get_tag_map(jsonb)
 column span_tags of view span
 column resource_tags of view span
 column event_tags of view event
 column span_tags of view event
 column resource_tags of view event
 column span_tags of view link
 column resource_tags of view link
 column linked_span_tags of view link
 column linked_resource_tags of view link
 column link_tags of view link
(43 rows)
```

### CODE REVIEW

**Review by jgpruitt — APPROVED** [review]

**Review by JamesGuthrie — APPROVED** [review]
LGTM. Note that I re-added all of `test_tag_funs` except for the bit which didn't make sense anymore.

**Comment by pgnickb** [comment]
Shall we perhaps add a 
```SQL
DROP DOMAIN IF EXISTS ps_trace.tag_map CASCADE;
```
into idempotent stuff?
Also maybe even:
```SQL
DROP DOMAIN IF EXISTS ps_trace.tag_map_old CASCADE;
```

**Review by sumerman — APPROVED** [review]
@JamesGuthrie did the bulk of re-instating tests that used the old API. And I converted the last one. We shouldn't remove them, as they are intended to test that relying on `jsonb_digest` doesn't break tag map API. Now I think it's good to go.

**Comment by sumerman** [comment]
> Shall we perhaps add a
> 
> ```sql
> DROP DOMAIN IF EXISTS ps_trace.tag_map CASCADE;
> ```
> 
> into idempotent stuff? Also maybe even:
> 
> ```sql
> DROP DOMAIN IF EXISTS ps_trace.tag_map_old CASCADE;
> ```

Why would we do that?

**Pull request merged**
