### PR TITLE
Fix unqualified casts in SQL scripts

### PR DESCRIPTION
**Pull request by JamesGuthrie**

### CODE REVIEW

**Review by sumerman — APPROVED** [review]
the change itself looks good, but AFAICT it's far from being exhaustive.

**Review by cevian — APPROVED** [review]

**Comment by JamesGuthrie** [comment]
> the change itself looks good, but AFAICT it's far from being exhaustive.

Do you have examples of cases which you think are not being correctly caught?

**Comment by sumerman** [comment]
> > the change itself looks good, but AFAICT it's far from being exhaustive.
> 
> Do you have examples of cases which you think are not being correctly caught?

E.g. `007-matcher-operators.sql` has more unqualified casts.

**Comment by JamesGuthrie** [comment]
> > > the change itself looks good, but AFAICT it's far from being exhaustive.
> > 
> > 
> > Do you have examples of cases which you think are not being correctly caught?
> 
> E.g. `007-matcher-operators.sql` has more unqualified casts.

Interestingly, `::int` does not qualify as an unqualified cast, because the parser expands it to `pg_catalog.integer`.

**Pull request merged**
