### PR TITLE
Simultaneous Promscale versions

### PR DESCRIPTION
**Pull request by sumerman**
Addresses #113 

Verified following a procedure, similar to the one described [here](https://github.com/timescale/timescaledb-docker-ha/pull/227#issuecomment-1101568154)

### CODE REVIEW

**Review by JamesGuthrie — CHANGES_REQUESTED** [review]
Do we not also need to make changes to the github workflow to make it build the latest alpine image with the correct versions in it?

**Comment by sumerman** [comment]
> Do we not also need to make changes to the github workflow to make it build the latest alpine image with the correct versions in it?

AFAICT `timescaledev/promscale-extension:latest-ts2-pg${PG_VERSION}` was published by hand in the past. I'm not sure if I should be changing that. Assuming the `latest-ts2-pg${PG_VERSION}` tag is correctly maintained in the future the current change should suffice as every subsequent image would include everything the previous version had.

**Comment by JamesGuthrie** [comment]
> > Do we not also need to make changes to the github workflow to make it build the latest alpine image with the correct versions in it?
> 
> AFAICT `timescaledev/promscale-extension:latest-ts2-pg${PG_VERSION}` was published by hand in the past. I'm not sure if I should be changing that. Assuming the `latest-ts2-pg${PG_VERSION}` tag is correctly maintained in the future the current change should suffice as every subsequent image would include everything the previous version had.

I think that it was published by hand in the past, but I thought that we changed that since the most recent release.

**Comment by sumerman** [comment]
> > > Do we not also need to make changes to the github workflow to make it build the latest alpine image with the correct versions in it?
> > 
> > 
> > AFAICT `timescaledev/promscale-extension:latest-ts2-pg${PG_VERSION}` was published by hand in the past. I'm not sure if I should be changing that. Assuming the `latest-ts2-pg${PG_VERSION}` tag is correctly maintained in the future the current change should suffice as every subsequent image would include everything the previous version had.
> 
> I think that it was published by hand in the past, but I thought that we changed that since the most recent release.

I can only see automated publishing to `ghcr.io/timescale/dev_promscale_extension:` that we build as a part of CI workflow. AFAICT release workflow builds and publishes packages, but not the image.

**Review by JamesGuthrie — APPROVED** [review]

**Pull request merged**
