### PR TITLE
Don't fail metric deletion if some tables or views are missing

### PR DESCRIPTION
**Pull request by oliora**
## Description

Due to a manual intervention to the database some tables or views for metrics may be deleted. It's nice if `drop_metric` can still work in this conditions and do a proper cleanup.

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

The change looks minor and internal enough that it does not need to be communicated to end users.

### CODE REVIEW

**Comment by sumerman** [comment]
Thanks a lot for the pull request. I'm looking into fixing our CI to allow it to pass.

**Review by cevian — APPROVED** [review]

**Comment by sumerman** [comment]
@oliora #459 just landed. Could you try and rebase your PR?

**Comment by oliora** [comment]
I’ll rebase instead of merging and update the pr

**Comment by oliora** [comment]
I had to create a new PR https://github.com/timescale/promscale_extension/pull/460

**Pull request closed without merging**
