### PR TITLE
Merge release 0.5.0 into master

### PR DESCRIPTION
**Pull request by cevian**

### CODE REVIEW

**Review by JamesGuthrie — CHANGES_REQUESTED** [review]
Can you please add the generated sql schema file to this commit with `cargo pgx schema --out sql/promscale--0.5.0.sql`.

**Review by sumerman — APPROVED** [review]

**Comment by cevian** [comment]
@JamesGuthrie done but can't say I loved it since we didnt do that for the alphas

**Comment by JamesGuthrie** [comment]
> @JamesGuthrie done but can't say I loved it since we didnt do that for the alphas

Ack. If we don't do this now, the`promscale--0.5.0.sql` file will be "lost to the ether" (ish, we could always get it back). We may also want to commit the upgrade script symlinks, but it's too late for me to pass judgement on that, and we can quite easily do that retroactively.

Also: holy large file batman.

**Review by JamesGuthrie — APPROVED** [review]
LGTM. 🤞

**Review by jgpruitt — APPROVED** [review]

**Pull request merged**
